#!/bin/csh -f
#PBS -l nodes=1:ppn=8:blade:intel:avx #:del_int_16_64
#PBS -l walltime=48:00:00
##PBS -q long
#PBS -o test.o
#PBS -e test.e

if ( $cnt > $cntmax ) exit

cd /data/sjpark/simulation_2ERM

#

set NODELIST = namd2.nodelist
set NODES    = `cat $PBS_NODEFILE | sort -u `

echo group main > $NODELIST
foreach node ( $NODES )
    echo host $node >> $NODELIST
end

#

set dir = /research/imlab/namd/NAMD_2.10_Linux-x86_64-multicore/

#

if ( $cnt == 0 ) then
    cp ../../../step8.0.namd junk.namd

    $dir/charmrun $dir/namd2 +p8 junk.namd | tee step8_${cnt}.out > /dev/null

    rm -f step8_${cnt}.restart.*
    @ cnt = ${cnt} + 1
endif

#

while ( $cnt <= $cntmax )
    sleep 60

    if ( ! -e  step8_${cnt}.coor ) then
	@ cxt = ${cnt} - 1
	if ( ! -e  step8_${cxt}.coor ) exit

	@ inputnum = ${cnt} - 1
	sed -e 's/inputnum/'${inputnum}'/g' ../../../step8.1.namd | sed -e 's/outputnum/'${cnt}'/g' > junk.namd
	$dir/charmrun $dir/namd2 +p8 junk.namd | tee step8_${cnt}.out > /dev/null

	sleep 60
	if ( ! -e  step8_${cnt}.coor ) exit
	rm -f step8_${cnt}.restart.*
    endif

    @ cnt = ${cnt} + 1
end

exit
